name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: cd ignite_lab_03 && npm ci --legacy-peer-deps

      - name: Build Storybook
        run: cd ignite_lab_03 && npm run build-storybook

      - name: Deploy Storybook
        run: cd ignite_lab_03 && npm run deploy-storybook -- --ci --existing-output-dir=ignite_lab_03/storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}